/******************************************************************************
    Copyright © 2012-2015 Martin Karsten

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
******************************************************************************/
#ifndef _asmdecl_h_
#define _asmdecl_h_ 1

#include "generic/basics.h"

// asm_functions.S
extern "C" void loadIDT(ptr_t idt, uint16_t size);
extern "C" void loadGDT(ptr_t gdt, uint16_t size);
extern "C" void clearLDT();
extern "C" void loadTR(uint16_t selector);

// syscall_wrapper.S
extern "C" void syscall_wrapper(void);
extern "C" void startUserCode(ptr_t arg1, ptr_t arg2, vaddr ksp, funcvoid2_t invoke, vaddr usp) __noreturn;

// isr_wrapper.S
extern "C" void isr_wrapper_0x00(void);
extern "C" void isr_wrapper_0x01(void);
extern "C" void isr_wrapper_0x02(void);
extern "C" void isr_wrapper_0x03(void);
extern "C" void isr_wrapper_0x04(void);
extern "C" void isr_wrapper_0x05(void);
extern "C" void isr_wrapper_0x06(void);
extern "C" void isr_wrapper_0x07(void);
extern "C" void isr_wrapper_0x08(void);
extern "C" void isr_wrapper_0x09(void);
extern "C" void isr_wrapper_0x0a(void);
extern "C" void isr_wrapper_0x0b(void);
extern "C" void isr_wrapper_0x0c(void);
extern "C" void isr_wrapper_0x0d(void);
extern "C" void isr_wrapper_0x0e(void);
extern "C" void isr_wrapper_0x0f(void);
extern "C" void isr_wrapper_0x10(void);
extern "C" void isr_wrapper_0x11(void);
extern "C" void isr_wrapper_0x12(void);
extern "C" void isr_wrapper_0x13(void);
extern "C" void isr_wrapper_0x14(void);
extern "C" void isr_wrapper_0x15(void);
extern "C" void isr_wrapper_0x16(void);
extern "C" void isr_wrapper_0x17(void);
extern "C" void isr_wrapper_0x18(void);
extern "C" void isr_wrapper_0x19(void);
extern "C" void isr_wrapper_0x1a(void);
extern "C" void isr_wrapper_0x1b(void);
extern "C" void isr_wrapper_0x1c(void);
extern "C" void isr_wrapper_0x1d(void);
extern "C" void isr_wrapper_0x1e(void);
extern "C" void isr_wrapper_0x1f(void);
extern "C" void isr_wrapper_0x20(void);
extern "C" void isr_wrapper_0x21(void);
extern "C" void isr_wrapper_0x22(void);
extern "C" void isr_wrapper_0x23(void);
extern "C" void isr_wrapper_0x24(void);
extern "C" void isr_wrapper_0x25(void);
extern "C" void isr_wrapper_0x26(void);
extern "C" void isr_wrapper_0x27(void);
extern "C" void isr_wrapper_0x28(void);
extern "C" void isr_wrapper_0x29(void);
extern "C" void isr_wrapper_0x2a(void);
extern "C" void isr_wrapper_0x2b(void);
extern "C" void isr_wrapper_0x2c(void);
extern "C" void isr_wrapper_0x2d(void);
extern "C" void isr_wrapper_0x2e(void);
extern "C" void isr_wrapper_0x2f(void);
extern "C" void isr_wrapper_0x30(void);
extern "C" void isr_wrapper_0x31(void);
extern "C" void isr_wrapper_0x32(void);
extern "C" void isr_wrapper_0x33(void);
extern "C" void isr_wrapper_0x34(void);
extern "C" void isr_wrapper_0x35(void);
extern "C" void isr_wrapper_0x36(void);
extern "C" void isr_wrapper_0x37(void);
extern "C" void isr_wrapper_0x38(void);
extern "C" void isr_wrapper_0x39(void);
extern "C" void isr_wrapper_0x3a(void);
extern "C" void isr_wrapper_0x3b(void);
extern "C" void isr_wrapper_0x3c(void);
extern "C" void isr_wrapper_0x3d(void);
extern "C" void isr_wrapper_0x3e(void);
extern "C" void isr_wrapper_0x3f(void);
extern "C" void isr_wrapper_0x40(void);
extern "C" void isr_wrapper_0x41(void);
extern "C" void isr_wrapper_0x42(void);
extern "C" void isr_wrapper_0x43(void);
extern "C" void isr_wrapper_0x44(void);
extern "C" void isr_wrapper_0x45(void);
extern "C" void isr_wrapper_0x46(void);
extern "C" void isr_wrapper_0x47(void);
extern "C" void isr_wrapper_0x48(void);
extern "C" void isr_wrapper_0x49(void);
extern "C" void isr_wrapper_0x4a(void);
extern "C" void isr_wrapper_0x4b(void);
extern "C" void isr_wrapper_0x4c(void);
extern "C" void isr_wrapper_0x4d(void);
extern "C" void isr_wrapper_0x4e(void);
extern "C" void isr_wrapper_0x4f(void);
extern "C" void isr_wrapper_0x50(void);
extern "C" void isr_wrapper_0x51(void);
extern "C" void isr_wrapper_0x52(void);
extern "C" void isr_wrapper_0x53(void);
extern "C" void isr_wrapper_0x54(void);
extern "C" void isr_wrapper_0x55(void);
extern "C" void isr_wrapper_0x56(void);
extern "C" void isr_wrapper_0x57(void);
extern "C" void isr_wrapper_0x58(void);
extern "C" void isr_wrapper_0x59(void);
extern "C" void isr_wrapper_0x5a(void);
extern "C" void isr_wrapper_0x5b(void);
extern "C" void isr_wrapper_0x5c(void);
extern "C" void isr_wrapper_0x5d(void);
extern "C" void isr_wrapper_0x5e(void);
extern "C" void isr_wrapper_0x5f(void);
extern "C" void isr_wrapper_0x60(void);
extern "C" void isr_wrapper_0x61(void);
extern "C" void isr_wrapper_0x62(void);
extern "C" void isr_wrapper_0x63(void);
extern "C" void isr_wrapper_0x64(void);
extern "C" void isr_wrapper_0x65(void);
extern "C" void isr_wrapper_0x66(void);
extern "C" void isr_wrapper_0x67(void);
extern "C" void isr_wrapper_0x68(void);
extern "C" void isr_wrapper_0x69(void);
extern "C" void isr_wrapper_0x6a(void);
extern "C" void isr_wrapper_0x6b(void);
extern "C" void isr_wrapper_0x6c(void);
extern "C" void isr_wrapper_0x6d(void);
extern "C" void isr_wrapper_0x6e(void);
extern "C" void isr_wrapper_0x6f(void);
extern "C" void isr_wrapper_0x70(void);
extern "C" void isr_wrapper_0x71(void);
extern "C" void isr_wrapper_0x72(void);
extern "C" void isr_wrapper_0x73(void);
extern "C" void isr_wrapper_0x74(void);
extern "C" void isr_wrapper_0x75(void);
extern "C" void isr_wrapper_0x76(void);
extern "C" void isr_wrapper_0x77(void);
extern "C" void isr_wrapper_0x78(void);
extern "C" void isr_wrapper_0x79(void);
extern "C" void isr_wrapper_0x7a(void);
extern "C" void isr_wrapper_0x7b(void);
extern "C" void isr_wrapper_0x7c(void);
extern "C" void isr_wrapper_0x7d(void);
extern "C" void isr_wrapper_0x7e(void);
extern "C" void isr_wrapper_0x7f(void);
extern "C" void isr_wrapper_0x80(void);
extern "C" void isr_wrapper_0x81(void);
extern "C" void isr_wrapper_0x82(void);
extern "C" void isr_wrapper_0x83(void);
extern "C" void isr_wrapper_0x84(void);
extern "C" void isr_wrapper_0x85(void);
extern "C" void isr_wrapper_0x86(void);
extern "C" void isr_wrapper_0x87(void);
extern "C" void isr_wrapper_0x88(void);
extern "C" void isr_wrapper_0x89(void);
extern "C" void isr_wrapper_0x8a(void);
extern "C" void isr_wrapper_0x8b(void);
extern "C" void isr_wrapper_0x8c(void);
extern "C" void isr_wrapper_0x8d(void);
extern "C" void isr_wrapper_0x8e(void);
extern "C" void isr_wrapper_0x8f(void);
extern "C" void isr_wrapper_0x90(void);
extern "C" void isr_wrapper_0x91(void);
extern "C" void isr_wrapper_0x92(void);
extern "C" void isr_wrapper_0x93(void);
extern "C" void isr_wrapper_0x94(void);
extern "C" void isr_wrapper_0x95(void);
extern "C" void isr_wrapper_0x96(void);
extern "C" void isr_wrapper_0x97(void);
extern "C" void isr_wrapper_0x98(void);
extern "C" void isr_wrapper_0x99(void);
extern "C" void isr_wrapper_0x9a(void);
extern "C" void isr_wrapper_0x9b(void);
extern "C" void isr_wrapper_0x9c(void);
extern "C" void isr_wrapper_0x9d(void);
extern "C" void isr_wrapper_0x9e(void);
extern "C" void isr_wrapper_0x9f(void);
extern "C" void isr_wrapper_0xa0(void);
extern "C" void isr_wrapper_0xa1(void);
extern "C" void isr_wrapper_0xa2(void);
extern "C" void isr_wrapper_0xa3(void);
extern "C" void isr_wrapper_0xa4(void);
extern "C" void isr_wrapper_0xa5(void);
extern "C" void isr_wrapper_0xa6(void);
extern "C" void isr_wrapper_0xa7(void);
extern "C" void isr_wrapper_0xa8(void);
extern "C" void isr_wrapper_0xa9(void);
extern "C" void isr_wrapper_0xaa(void);
extern "C" void isr_wrapper_0xab(void);
extern "C" void isr_wrapper_0xac(void);
extern "C" void isr_wrapper_0xad(void);
extern "C" void isr_wrapper_0xae(void);
extern "C" void isr_wrapper_0xaf(void);
extern "C" void isr_wrapper_0xb0(void);
extern "C" void isr_wrapper_0xb1(void);
extern "C" void isr_wrapper_0xb2(void);
extern "C" void isr_wrapper_0xb3(void);
extern "C" void isr_wrapper_0xb4(void);
extern "C" void isr_wrapper_0xb5(void);
extern "C" void isr_wrapper_0xb6(void);
extern "C" void isr_wrapper_0xb7(void);
extern "C" void isr_wrapper_0xb8(void);
extern "C" void isr_wrapper_0xb9(void);
extern "C" void isr_wrapper_0xba(void);
extern "C" void isr_wrapper_0xbb(void);
extern "C" void isr_wrapper_0xbc(void);
extern "C" void isr_wrapper_0xbd(void);
extern "C" void isr_wrapper_0xbe(void);
extern "C" void isr_wrapper_0xbf(void);
extern "C" void isr_wrapper_0xc0(void);
extern "C" void isr_wrapper_0xc1(void);
extern "C" void isr_wrapper_0xc2(void);
extern "C" void isr_wrapper_0xc3(void);
extern "C" void isr_wrapper_0xc4(void);
extern "C" void isr_wrapper_0xc5(void);
extern "C" void isr_wrapper_0xc6(void);
extern "C" void isr_wrapper_0xc7(void);
extern "C" void isr_wrapper_0xc8(void);
extern "C" void isr_wrapper_0xc9(void);
extern "C" void isr_wrapper_0xca(void);
extern "C" void isr_wrapper_0xcb(void);
extern "C" void isr_wrapper_0xcc(void);
extern "C" void isr_wrapper_0xcd(void);
extern "C" void isr_wrapper_0xce(void);
extern "C" void isr_wrapper_0xcf(void);
extern "C" void isr_wrapper_0xd0(void);
extern "C" void isr_wrapper_0xd1(void);
extern "C" void isr_wrapper_0xd2(void);
extern "C" void isr_wrapper_0xd3(void);
extern "C" void isr_wrapper_0xd4(void);
extern "C" void isr_wrapper_0xd5(void);
extern "C" void isr_wrapper_0xd6(void);
extern "C" void isr_wrapper_0xd7(void);
extern "C" void isr_wrapper_0xd8(void);
extern "C" void isr_wrapper_0xd9(void);
extern "C" void isr_wrapper_0xda(void);
extern "C" void isr_wrapper_0xdb(void);
extern "C" void isr_wrapper_0xdc(void);
extern "C" void isr_wrapper_0xdd(void);
extern "C" void isr_wrapper_0xde(void);
extern "C" void isr_wrapper_0xdf(void);
extern "C" void isr_wrapper_0xe0(void);
extern "C" void isr_wrapper_0xe1(void);
extern "C" void isr_wrapper_0xe2(void);
extern "C" void isr_wrapper_0xe3(void);
extern "C" void isr_wrapper_0xe4(void);
extern "C" void isr_wrapper_0xe5(void);
extern "C" void isr_wrapper_0xe6(void);
extern "C" void isr_wrapper_0xe7(void);
extern "C" void isr_wrapper_0xe8(void);
extern "C" void isr_wrapper_0xe9(void);
extern "C" void isr_wrapper_0xea(void);
extern "C" void isr_wrapper_0xeb(void);
extern "C" void isr_wrapper_0xec(void);
extern "C" void isr_wrapper_0xed(void);
extern "C" void isr_wrapper_0xee(void);
extern "C" void isr_wrapper_0xef(void);
extern "C" void isr_wrapper_0xf0(void);
extern "C" void isr_wrapper_0xf1(void);
extern "C" void isr_wrapper_0xf2(void);
extern "C" void isr_wrapper_0xf3(void);
extern "C" void isr_wrapper_0xf4(void);
extern "C" void isr_wrapper_0xf5(void);
extern "C" void isr_wrapper_0xf6(void);
extern "C" void isr_wrapper_0xf7(void);
extern "C" void isr_wrapper_0xf8(void);
extern "C" void isr_wrapper_0xf9(void);
extern "C" void isr_wrapper_0xfa(void);
extern "C" void isr_wrapper_0xfb(void);
extern "C" void isr_wrapper_0xfc(void);
extern "C" void isr_wrapper_0xfd(void);
extern "C" void isr_wrapper_0xfe(void);
extern "C" void isr_wrapper_0xff(void);

#endif /* _asmdecl_h_ */
